title:   Alissa Phan
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
Hello and welcome to my portfolio page! As a BI Analyst, I'm excited to share my passion for data analysis with you and provide a glimpse into my work. Please take a moment to browse through my projects and feel free to contact me if you have any questions or comments.
  <br><br><br>
  <a href="https://www.linkedin.com/in/alissa-phan/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/alissa8505">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/alissaphan/67241f3fc52c498f976b0e56fb115621">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
